// Generated by CoffeeScript 1.3.1
(function() {
  var NStatus,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  NStatus = (function() {

    NStatus.name = 'NStatus';

    function NStatus() {
      this.update_display = __bind(this.update_display, this);

      this.fetch_data = __bind(this.fetch_data, this);
      this.nstatus = {};
      this.fetch_data('nstatus.json');
    }

    NStatus.prototype.fetch_data = function(data_source) {
      var _this = this;
      return $.getJSON(data_source, function(response) {
        console.log(response);
        _this.nstatus = response;
        return _this.update_display();
      });
    };

    NStatus.prototype.update_display = function() {
      var days_since_sick, illnesses, last_date;
      illnesses = this.nstatus.illness;
      last_date = illnesses[0].date;
      days_since_sick = moment(last_date, "MMDDYYYY").fromNow();
      $('.days_since_sick').html(days_since_sick);
      return $('.days_since_sick').prop('title', illnesses[0].description);
    };

    return NStatus;

  })();

  $(function() {
    return window.nstatus = new NStatus();
  });

}).call(this);
